export const CATEGORIES: string[] = [
  "finance",
  "health",
  "education",
  "entertainment",
  "e-commerce",
  "productivity",
  "social media",
  "gaming",
  "travel",
  "real estate",
  "food",
  "beverages",
  "fitness",
  "environment",
  "transportation",
  "security",
  "logistics",
  "agriculture",
  "art",
  "news",
  "communication",
  "automation",
  "blockchain",
  "crypto",
  "legal",
  "human resources",
  "customer service",
  "project management",
  "home automation",
  "virtual reality",
  "augmented reality",
  "cloud computing",
  "cybersecurity",
  "mental health",
  "elder care",
  "child care",
  "nonprofit",
  "government",
  "community service",
  "music",
  "photography",
  "video production",
  "weather",
  "personal finance",
  "languages",
  "career",
  "relationships",
  "event planning",
  "pet care",
  "fashion",
  "beauty",
  "automotive",
  "supply chain",
  "waste",
  "resources",
  "geospatial",
  "biotechnology",
  "telemedicine",
  "remote work",
  "collaboration",
  "content creation",
  "documentation",
  "inventory",
  "fintech",
  "insurtech",
  "proptech",
  "edutainment",
  "heritage",
  "spirituality",
  "motivation",
  "shopping",
  "marketplace",
  "crowdsourcing",
  "freelancing",
  "networking",
  "marketing",
  "advertising",
  "public relations",
  "branding",
  "ux design",
  "ui design",
  "research",
  "qa testing",
  "optimization",
  "compliance",
  "regulatory",
  "library",
  "museum",
  "sports",
  "betting",
  "ticketing",
];
